---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  es2020: true
  webextensions: true
  browser: true

extends:
  - 'airbnb-base'
  - "plugin:prettier/recommended"

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
